config/routes.rb
Rails.application.routes.draw do

  root "posts#index"
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :image, presence: true

	has_attached_file :image, styles: { :medium => "640x640" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @instagram = Instagram.user_recent_media("174431290", {:count => 1})
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new 
  	@post = Post.new
  end

  def create
  	@post = Post.create(post_params)
  	if @post.save
  		flash[:success] = "Your post has been created."
  		redirect_to @post
  	else 
  		flash[:alert] = "Halt, you fiend! You need an image to post here!"
  		render :new
  	end
  end

  def show
  	@post = Post.find(params[:id])
  end	

  private

  def post_params
  	params.require(:post).permit(:caption, :image)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_for(flash_type) {
		:success => 'alert-success',
		:error => 'alert-danger',
        :alert => 'alert-warning',
        :notice => 'alert-info'
    	}[flash_type.to_sym] || [flash_type.to_s]
  	end
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= @instagram.each do |instagram| %>
<%= image_tag instagram.images.standard_resolution.url %>
<% end %>

app/views/layouts/application.html.erb
<html>
	<head>
		<meta content="text/html" charset="UTF-8" http-equiv="Content-Type">
		<title> Biophilia Fit </title>
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, class: [:alert, alert_for(name)]%>
		<%end%>
		<%= yield %>
	</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BiophiliaFit
    %nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "Photogram", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "New Post", new_post_path
        %li
          = link_to "Login", '#'
        %li
          = link_to "Register", '#'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield
    
    -flash.each do |name, msg|
      = content_tag :div, msg, class: [:alert, alert_for(name)]

app/views/posts/index.html.erb
<h1> Biophilia Fit </h1>
<%= link_to "New Post", new_post_path %>

<div class = "posts-wrapper row">
	<% @posts.each do |post| %>
		<div class = "post">
			<div class = "name">
				<h1> Cody Mckeon </h1>
			</div>
			<div class = "image center-block">
				<%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
				<p><%= post.caption %></p>
			</div>
		</div>
	<% end %>
</div>
		
			
		

app/views/posts/new.html.erb
<div class = "form-wrapper">
<%= simple_form_for @post, html: { class: 'form-horizonatl', multipart: true } do |f| %>
	<div class = "form-group">
		<%= f.input :image %>
	</div>

	<div class = "form-group text-center">
		<%= f.input :caption %>
	</div>

	<div class = "form-group text-center">
		<%= f.button :submit, class: 'btn-success' %>
	</div>
<%end%>
</div>

app/views/posts/show.html.erb
<div class = "posts-wrapper row">
	<div class = "post">
		<div class = "name">
			<h1> Cody Mckeon </h1>
			<div class = "image center-block">
				<%= image_tag @post.image.url(:medium) %>
			</div>
			<p>
			<%= @post.caption %>
			</p>
			<div class = "text-center">
				<%= link_to "Cancel", posts_path %>
			</div>
	</div>
</div>